I couldn't upload any file. I didn't finished the exercise but I had my jupyter notebook to upload. HOwever, It displayed an error: **Uploads are disable**
I hope I have a chance for the next Datathon.
